// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdA9ECpPdEoukmymXWTyfews5RQ3SpM88',
    appId: '1:900486954577:web:50346565052f8b57af8270',
    messagingSenderId: '900486954577',
    projectId: 'cloud-login-app-38d3a',
    authDomain: 'cloud-login-app-38d3a.firebaseapp.com',
    storageBucket: 'cloud-login-app-38d3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJKiEqU0h0dx1p_zP5ns6sENRiGBXboRk',
    appId: '1:900486954577:ios:347e1eed36c2dee1af8270',
    messagingSenderId: '900486954577',
    projectId: 'cloud-login-app-38d3a',
    storageBucket: 'cloud-login-app-38d3a.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJKiEqU0h0dx1p_zP5ns6sENRiGBXboRk',
    appId: '1:900486954577:ios:347e1eed36c2dee1af8270',
    messagingSenderId: '900486954577',
    projectId: 'cloud-login-app-38d3a',
    storageBucket: 'cloud-login-app-38d3a.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
